handle unicode error when loading log.las
andymcdgeo/las_explorer pull request #4
Opened 2021-01-13 12:31 UTC by mlr07

Modified `load_data` func to handle las files with strange encoding: 

1. Read log to bytes with built in read()
2. Build a StringIO object from bytes
3. Decoded object to string with forced windows-1252 encoding (this is the fix)
4. Read to las object and dataframe via lasio

Explicitly handled `UnicodeDecodeError` in try block. 

Test logs loaded and displayed correctly after change (screenshot). Note: these logs are also missing header section ~P, but I think lasio handles that internally. 

![image](https://user-images.githubusercontent.com/43920353/104452271-62f33d80-5568-11eb-9a31-3d3555391767.png)

2021-01-13 22:00 UTC, andymcdgeo requested changes
Minor change needed in the except block. Changing print to st.error will allow the error to be shown to the Streamlit app user.

2021-01-13 22:00 UTC, andymcdgeo commented on app.py
> +            print(f"error loading log.las: {e}")
As Streamlit runs on a server the user won't see the print statements. This would probably be best as `st.error(f'Error loading LAS file: {e}`

2021-01-13 22:02 UTC, andymcdgeo commented
Thanks Matt. I have tested this with my files and yours, all seems to be working.
I have suggested one minor change before I pull it into the master branch. I am still new to managing PRs - I wasn't sure if I could edit the PR code to fix it or if it needs to come from you :)

2021-01-14 01:08 UTC, mlr07 commented on app.py
> +            print(f"error loading log.las: {e}")
That is a  good point, was thinking in terminal mode. Will add `st.error` to exception.

2021-01-14 01:09 UTC, mlr07 commented
I am still trying to figure out the PR workflow too! I think I need to make the changes and resubmit.

2021-01-14 18:35 UTC, andymcdgeo approved these changes
All good.

2021-01-14 18:35 UTC, merged

2021-01-14 18:35 UTC, andymcdgeo commented
Thanks Matt. I will pull this into master.